# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --include=dev

# Bundle app source
COPY . .

# Build the Next.js app for production
RUN npm run build 
# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npx", "vite", "preview", "--port", "3000", "--host", "0.0.0.0"]